# fly.toml app configuration file generated for paintweb on 2024-06-08T12:39:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'paintweb'
primary_region = 'lhr'

[build]
image = "python:3.12.3" # Specify the Python version

[env]
PYTHON_ENV_PATH = "/app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
